version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./apps/frontend/dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - calculator-network

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - calculator-network

networks:
  calculator-network:
    external: true
